DjangoMusicHistory/history/urls.py
from django.urls import path
from . import views

app_name = 'history'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('artists/', views.ArtistListTemplateView.as_view(), name="artists"),
    path('artists/<int:pk>/', views.ArtistDetailView.as_view(), name="artist_detail")
]

DjangoMusicHistory/music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls')),
]

DjangoMusicHistory/history/models.py
from django.db import models


class Artist(models.Model):
    """Model the data of a musical artist"""

    Artist_ID = models.AutoField(primary_key=True)
    Artist_Name = models.CharField(max_length=140)
    Year_Established = models.PositiveSmallIntegerField(blank=True, null=True)

    class Meta:
        verbose_name = ("Artist")
        verbose_name_plural = ("Artists")

    def __str__(self):
        return self.Artist_Name

    def get_absolute_url(self):
        return reverse("Artist_detail", kwargs={"pk": self.pk})


class Song(models.Model):
    """Model the data of a song track"""

    Song_ID = models.AutoField(primary_key=True)
    Song_Title = models.CharField(max_length=140)
    Song_Length = models.DurationField(blank=True, null=True)
    Release_Date = models.DateField(auto_now=False, auto_now_add=False)
    Genre_ID = models.ForeignKey("Genre", on_delete=models.CASCADE)
    Artist_ID = models.ForeignKey("Artist", on_delete=models.CASCADE)
    Album_ID = models.ForeignKey("Album", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Song")
        verbose_name_plural = ("Songs")

    def __str__(self):
        return self.Song_Title

    def get_absolute_url(self):
        return reverse("Song_detail", kwargs={"pk": self.pk})


class Album(models.Model):
    """Model the data of an album"""

    Album_ID = models.AutoField(primary_key=True)
    Album_Title = models.CharField(max_length=140, blank=True, null=True)
    Release_Date = models.DateField(auto_now=False, auto_now_add=False)
    Album_Length = models.DurationField(blank=True, null=True)
    Album_Label = models.CharField(max_length=50)
    Artist_ID = models.ForeignKey("Artist", on_delete=models.CASCADE)
    Genre_ID = models.ForeignKey("Genre", on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Album")
        verbose_name_plural = ("Albums")

    def __str__(self):
        return self.Album_Title

    def get_absolute_url(self):
        return reverse("Album_detail", kwargs={"pk": self.pk})


class Genre(models.Model):
    """Model the data of a genre"""

    Genre_ID = models.AutoField(primary_key=True)
    Genre_Name = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("Genre")
        verbose_name_plural = ("Genres")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Genre_detail", kwargs={"pk": self.pk})

DjangoMusicHistory/history/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, TemplateView, FormView, DetailView, CreateView
from history.models import Artist, Song, Album, Genre


class IndexView(TemplateView):
    """Creates view for index"""

    template_name = "history/index.html"

    # ?Not sure what location is for?

    def location(self):
        return 'home'


class ArtistListTemplateView(TemplateView):
    template_name = 'history/artists.html'

    def artist_list(self):
        artists = Artist.objects.all()
        return artists


class ArtistDetailView(DetailView):
    model = Artist


class SongListView(ListView):
    model = Song
    context_object_name = 'song_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = "songs"
        return context


class SongDetailView(DetailView):
    model = Song

DjangoMusicHistory/history/templates/history/artist_list.html
{% extends "history/index.html" %} {% block main_stuff %} {% include "history/nav_bar.html" with nav_location=location %}

<h1>These are made up singers.</h1>

<ul>
    {% for artist in artist_list %}
    <li>
        <a href="{% url 'history:artist_detail' artist.id %}">{{artist.name}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock main_stuff %}

DjangoMusicHistory/history/templates/history/artists.html
{% extends "history/index.html" %} {% block main_stuff %}
<h1>These are the singers in my database.</h1>

<ul>
    {% for artist in view.artist_list %}
    <li>
        <a href="{% url 'history:artist_detail' artist.id %}">{{artist.name}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock main_stuff %}

DjangoMusicHistory/history/templates/history/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'history/main.css' %}" />

<h1>This is my music collection. Keep out.</h1>

{% block main_stuff %} {% include "history/nav_bar.html" with nav_location=view.location %}
<img src="{% static 'history/images/dire_straits.jpg' %}" alt="dire straits"> {% endblock main_stuff %}

DjangoMusicHistory/history/templates/history/nav_bar.html
<nav>
    {% if nav_location != 'artists' %}
    <form action="/history/artists" method='get'>
        <input type="submit" value="View My Artists">
    </form>
    {% endif %} {% if nav_location != 'songs' %}
    <form action="/history/songs" method="get">
        <input type="submit" value="View My Songs">
    </form>
    {% endif %} {% if nav_location != 'home' %}
    <form action="/history/" method="get">
        <input type="submit" value="Home">
    </form>
    {% endif %} {% if nav_location != 'add_artist' %}
    <form action="/history/artists/add" method="get">
        <input type="submit" value="Add Artist">
    </form>
    {% endif %}


</nav>